scripts: use new mountpoint /rom for rootdev

diff --git a/files/openwrt-backup b/files/openwrt-backup
--- a/files/openwrt-backup
+++ b/files/openwrt-backup
@@ -172,8 +172,11 @@ gen_fstab() {
     if [[ -z "${ROOT_PTNAME}" ]]; then
         ROOT_PTNAME="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
         if [[ -z "${ROOT_PTNAME}" ]]; then
-            echo "Cannot find the partition corresponding to the root file system!"
-            exit 1
+            ROOT_PTNAME="$(df /rom | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
+            if [[ -z "${ROOT_PTNAME}" ]]; then
+                echo "Cannot find the partition corresponding to the root file system!"
+                exit 1
+            fi
         fi
     fi
 
@@ -225,7 +228,7 @@ config global
 	option check_fs '0'
 
 config mount
-	option target '/overlay'
+	option target '/rom'
 	option uuid '${ROOT_UUID}'
 	option enabled '1'
 	option enabled_fsck '1'
diff --git a/files/openwrt-install-amlogic b/files/openwrt-install-amlogic
--- a/files/openwrt-install-amlogic
+++ b/files/openwrt-install-amlogic
@@ -67,7 +67,15 @@ fi
 root_devname=$(df / | tail -n1 | awk '{print $1}' | awk -F '\/' '{print substr($3, 1, length($3)-2)}')
 if [[ -z "${root_devname}" ]]; then
     root_devname="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '\/' '{print substr($3, 1, length($3)-2)}')"
+    if [[ -z "${root_devname}" ]]; then
+        root_devname="$(df /rom | tail -n1 | awk '{print $1}' | awk -F '\/' '{print substr($3, 1, length($3)-2)}')"
+        if [[ -z "${root_devname}" ]]; then
+            echo "Cannot find the partition corresponding to the root file system!"
+            exit 1
+        fi
+    fi
 fi
+
 if lsblk -l | grep -E "^${root_devname}boot0" >/dev/null; then
     echo "you are running in emmc mode, please boot system with usb or tf card!"
     exit 1
@@ -616,7 +624,7 @@ config  global
         option check_fs '0'
 
 config  mount
-        option target '/overlay'
+        option target '/rom'
         option uuid '${ROOTFS1_UUID}'
         option enabled '1'
         option enabled_fsck '1'
diff --git a/files/openwrt-update-amlogic b/files/openwrt-update-amlogic
--- a/files/openwrt-update-amlogic
+++ b/files/openwrt-update-amlogic
@@ -36,8 +36,11 @@ ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
 if [[ -z "${ROOT_PTNAME}" ]]; then
     ROOT_PTNAME="$(df /overlay | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
     if [[ -z "${ROOT_PTNAME}" ]]; then
-        echo "Cannot find the partition corresponding to the root file system!"
-        exit 1
+        ROOT_PTNAME="$(df /rom | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')"
+        if [[ -z "${ROOT_PTNAME}" ]]; then
+            echo "Cannot find the partition corresponding to the root file system!"
+            exit 1
+        fi
     fi
 fi
 
@@ -518,7 +521,7 @@ config  global
         option check_fs '0'
 
 config  mount
-        option target '/overlay'
+        option target '/rom'
         option uuid '${NEW_ROOT_UUID}'
         option enabled '1'
         option enabled_fsck '1'
