Support update kernel and firmware in TF/USB

diff --git a/files/openwrt-kernel b/files/openwrt-kernel
--- a/files/openwrt-kernel
+++ b/files/openwrt-kernel
@@ -52,12 +52,32 @@ fi
 echo -e "Current device: ${MYDEVICE_NAME} [${MYDTB_FILE}]"
 sleep 3
 
-EMMC_NAME=$(lsblk -l -o NAME | grep -oE '(mmcblk[0-9]?boot0)' | sed "s/boot0//g")
-P4_PATH="/mnt/${EMMC_NAME}p4"
+# Find the partition where root is located
+ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
+if [ "${ROOT_PTNAME}" == "" ];then
+    echo "Cannot find the partition corresponding to the root file system!"
+    exit 1
+fi
+
+# Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
+case ${ROOT_PTNAME} in
+       mmcblk?p[1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')
+                      PARTITION_NAME="p"
+                      LB_PRE="EMMC_"
+                      ;;
+    [hsv]d[a-z][1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')
+                      PARTITION_NAME=""
+                      LB_PRE=""
+                      ;;
+                   *) echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
+                      exit 1
+                      ;;
+esac
+
+P4_PATH="/mnt/${EMMC_NAME}${PARTITION_NAME}4"
 
 # Move kernel related files to the ${P4_PATH} directory
 mv -f /tmp/upload/* ${P4_PATH}/ 2>/dev/null && sync
-mv -f ${P4_PATH}/.tmp_upload/* ${P4_PATH}/ 2>/dev/null && sync
 
 if  [ $( ls ${P4_PATH}/*.tar.gz -l 2>/dev/null | grep "^-" | wc -l ) -ge 3 ]; then
 
@@ -108,7 +128,7 @@ if  [ $( ls ${P4_PATH}/*.tar.gz -l 2>/dev/null | grep "^-" | wc -l ) -ge 3 ]; th
 else
     echo -e "Please upload the kernel files."
     echo -e "Upload method: system menu → Amlogic Service → Manually Upload Update"
-    echo -e "Specify method: Place the kernel file in [ /mnt/${EMMC_NAME}p4/ ]"
+    echo -e "Specify method: Place the kernel file in [ /mnt/${EMMC_NAME}${PARTITION_NAME}4/ ]"
     echo -e "After upload the kernel file, run again."
     exit 1
 fi
