Support update kernel and firmware in TF/USB

diff --git a/files/openwrt-update-rockchip b/files/openwrt-update-rockchip
--- a/files/openwrt-update-rockchip
+++ b/files/openwrt-update-rockchip
@@ -36,18 +36,30 @@ fi
 echo -e "Current device: ${MYDEVICE_NAME} [ ${SOC} ]"
 sleep 3
 
-EMMC_NAME=$(lsblk | grep -oE '(mmcblk[0-9])' | sort | uniq)
-if [ "${EMMC_NAME}" == "" ]; then
-    echo "The system did not find any available disk devices!!!"
-    exit 1
-elif [[ "$(echo "${EMMC_NAME}" | awk -F 'mmcblk' '{print NF-1}')" -ne "1" ]]; then
-    echo "Please remove the more SD-card and try again."
+# Find the partition where root is located
+ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
+if [ "${ROOT_PTNAME}" == "" ];then
+    echo "Cannot find the partition corresponding to the root file system!"
     exit 1
 fi
 
-cd /mnt/${EMMC_NAME}p4/
+# Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
+case ${ROOT_PTNAME} in
+       mmcblk?p[1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')
+                      PARTITION_NAME="p"
+                      LB_PRE="EMMC_"
+                      ;;
+    [hsv]d[a-z][1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')
+                      PARTITION_NAME=""
+                      LB_PRE=""
+                      ;;
+                   *) echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
+                      exit 1
+                      ;;
+esac
+
+cd /mnt/${EMMC_NAME}${PARTITION_NAME}4/
 mv -f /tmp/upload/* . 2>/dev/null && sync
-mv -f .tmp_upload/* . 2>/dev/null && sync
 
 if [[ "${IMG_NAME}" == *.img ]]; then
     echo -e "Update using [ ${IMG_NAME} ] file. Please wait a moment ..."
@@ -78,7 +90,7 @@ elif [ $( ls *.zip -l 2>/dev/null | grep "^-" | wc -l ) -ge 1 ]; then
 else
     echo -e "Please upload or specify the update openwrt firmware file."
     echo -e "Upload method: system menu → Amlogic Service → Manually Upload Update"
-    echo -e "Specify method: Place the openwrt firmware file in [ /mnt/${EMMC_NAME}p4/ ]"
+    echo -e "Specify method: Place the openwrt firmware file in [ /mnt/${EMMC_NAME}${PARTITION_NAME}4/ ]"
     echo -e "The supported file suffixes are: *.img, *.img.xz, *.img.gz, *.7z, *.zip"
     echo -e "After upload the openwrt firmware file, run again."
     exit 1
@@ -123,11 +135,11 @@ ROOT_NAME=$(echo $ROOT_PART_MSG | awk '{print $1}')
 ROOT_PATH=$(echo $ROOT_PART_MSG | awk '{print $2}')
 ROOT_UUID=$(echo $ROOT_PART_MSG | awk '{print $4}')
 case $ROOT_NAME in 
-    ${EMMC_NAME}p2) NEW_ROOT_NAME=${EMMC_NAME}p3
-                    NEW_ROOT_LABEL=EMMC_ROOTFS2
+    ${EMMC_NAME}${PARTITION_NAME}2) NEW_ROOT_NAME="${EMMC_NAME}${PARTITION_NAME}3"
+                    NEW_ROOT_LABEL="${LB_PRE}ROOTFS2"
                     ;;
-    ${EMMC_NAME}p3) NEW_ROOT_NAME=${EMMC_NAME}p2
-                    NEW_ROOT_LABEL=EMMC_ROOTFS1
+    ${EMMC_NAME}${PARTITION_NAME}3) NEW_ROOT_NAME="${EMMC_NAME}${PARTITION_NAME}2"
+                    NEW_ROOT_LABEL="${LB_PRE}ROOTFS1"
                     ;;
     *) echo "The root partition location is invalid, so it cannot be upgraded with this script!"
                     exit 1
@@ -278,7 +290,7 @@ for src in $COPY_SRC;do
     echo "done"
 done
 
-SHFS="/mnt/${EMMC_NAME}p4"
+SHFS="/mnt/${EMMC_NAME}${PARTITION_NAME}4"
 echo "Modify config files ... "
 if [ -x ./usr/sbin/balethirq.pl ];then
     if grep "balethirq.pl" "./etc/rc.local";then
