Support TF card update

diff --git a/files/openwrt-backup b/files/openwrt-backup
--- a/files/openwrt-backup
+++ b/files/openwrt-backup
@@ -92,11 +92,25 @@ backup() {
 }
 
 restore() {
-    EMMC_NAME=$(lsblk | grep -oE '(mmcblk[0-9])' | sort | uniq)
+    # Find the partition where root is located
+    ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
+    if [ "${ROOT_PTNAME}" == "" ];then
+        echo "Cannot find the partition corresponding to the root file system!"
+        exit 1
+    fi
+
+    # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
+    case ${ROOT_PTNAME} in
+           mmcblk?p[1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}');;
+        [hsv]d[a-z][1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}');;
+                       *) echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
+                          exit 1
+                       ;;
+    esac
+
     [ -d "${BACKUP_DIR}" ] || mkdir -p "${BACKUP_DIR}"
     [ -f "/tmp/upload/${BACKUP_NAME}" ] && mv -f "/tmp/upload/${BACKUP_NAME}" ${BACKUP_FILE}
     [ -f "/mnt/${EMMC_NAME}p4/${BACKUP_NAME}" ] && mv -f "/mnt/${EMMC_NAME}p4/${BACKUP_NAME}" ${BACKUP_FILE}
-    [ -f "/mnt/${EMMC_NAME}p4/.tmp_upload/${BACKUP_NAME}" ] && mv -f "/mnt/${EMMC_NAME}p4/.tmp_upload/${BACKUP_NAME}" ${BACKUP_FILE}
     sync
 
     if [ -f "${BACKUP_FILE}" ]; then
diff --git a/files/openwrt-kernel b/files/openwrt-kernel
--- a/files/openwrt-kernel
+++ b/files/openwrt-kernel
@@ -52,12 +52,26 @@ fi
 echo -e "Current device: ${MYDEVICE_NAME} [${MYDTB_FILE}]"
 sleep 3
 
-EMMC_NAME=$(lsblk -l -o NAME | grep -oE '(mmcblk[0-9]?boot0)' | sed "s/boot0//g")
+# Find the partition where root is located
+ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
+if [ "${ROOT_PTNAME}" == "" ];then
+    echo "Cannot find the partition corresponding to the root file system!"
+    exit 1
+fi
+
+# Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
+case ${ROOT_PTNAME} in
+       mmcblk?p[1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}');;
+    [hsv]d[a-z][1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}');;
+                   *) echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
+                      exit 1
+                   ;;
+esac
+
 P4_PATH="/mnt/${EMMC_NAME}p4"
 
 # Move kernel related files to the ${P4_PATH} directory
 mv -f /tmp/upload/* ${P4_PATH}/ 2>/dev/null && sync
-mv -f ${P4_PATH}/.tmp_upload/* ${P4_PATH}/ 2>/dev/null && sync
 
 if  [ $( ls ${P4_PATH}/*.tar.gz -l 2>/dev/null | grep "^-" | wc -l ) -ge 3 ]; then
 
diff --git a/files/openwrt-update-allwinner b/files/openwrt-update-allwinner
--- a/files/openwrt-update-allwinner
+++ b/files/openwrt-update-allwinner
@@ -31,18 +31,24 @@ else
     sleep 3
 fi
 
-EMMC_NAME=$(lsblk | grep -oE '(mmcblk[0-9])' | sort | uniq)
-if [ "${EMMC_NAME}" == "" ]; then
-    echo "The system did not find any available disk devices!!!"
-    exit 1
-elif [[ "$(echo "${EMMC_NAME}" | awk -F 'mmcblk' '{print NF-1}')" -ne "1" ]]; then
-    echo "Please remove the more SD-card and try again."
+# Find the partition where root is located
+ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
+if [ "${ROOT_PTNAME}" == "" ];then
+    echo "Cannot find the partition corresponding to the root file system!"
     exit 1
 fi
 
+# Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
+case ${ROOT_PTNAME} in
+       mmcblk?p[1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}');;
+    [hsv]d[a-z][1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}');;
+                   *) echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
+                      exit 1
+                   ;;
+esac
+
 cd /mnt/${EMMC_NAME}p4/
 mv -f /tmp/upload/* . 2>/dev/null && sync
-mv -f .tmp_upload/* . 2>/dev/null && sync
 
 if [[ "${IMG_NAME}" == *.img ]]; then
     echo -e "Update using [ ${IMG_NAME} ] file. Please wait a moment ..."
