tidy up codes

diff --git a/files/openwrt-update-allwinner b/files/openwrt-update-allwinner
--- a/files/openwrt-update-allwinner
+++ b/files/openwrt-update-allwinner
@@ -33,24 +33,27 @@ fi
 
 # Find the partition where root is located
 ROOT_PTNAME=$(df / | tail -n1 | awk '{print $1}' | awk -F '/' '{print $3}')
-if [ "${ROOT_PTNAME}" == "" ];then
+if [ "${ROOT_PTNAME}" == "" ]; then
     echo "Cannot find the partition corresponding to the root file system!"
     exit 1
 fi
 
 # Find the disk where the partition is located, only supports mmcblk?p? sd?? hd?? vd?? and other formats
 case ${ROOT_PTNAME} in
-       mmcblk?p[1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')
-                      PARTITION_NAME="p"
-                      LB_PRE="EMMC_"
-                      ;;
-    [hsv]d[a-z][1-4]) EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')
-                      PARTITION_NAME=""
-                      LB_PRE=""
-                      ;;
-                   *) echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
-                      exit 1
-                      ;;
+mmcblk?p[1-4])
+    EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-2)}')
+    PARTITION_NAME="p"
+    LB_PRE="EMMC_"
+    ;;
+[hsv]d[a-z][1-4])
+    EMMC_NAME=$(echo ${ROOT_PTNAME} | awk '{print substr($1, 1, length($1)-1)}')
+    PARTITION_NAME=""
+    LB_PRE=""
+    ;;
+*)
+    echo "Unable to recognize the disk type of ${ROOT_PTNAME}!"
+    exit 1
+    ;;
 esac
 
 cd /mnt/${EMMC_NAME}${PARTITION_NAME}4/
@@ -58,30 +61,30 @@ mv -f /tmp/upload/* . 2>/dev/null && sync
 
 if [[ "${IMG_NAME}" == *.img ]]; then
     echo -e "Update using [ ${IMG_NAME} ] file. Please wait a moment ..."
-elif [ $( ls *.img -l 2>/dev/null | grep "^-" | wc -l ) -ge 1 ]; then
-    IMG_NAME=$( ls *.img | head -n 1 )
+elif [ $(ls *.img -l 2>/dev/null | grep "^-" | wc -l) -ge 1 ]; then
+    IMG_NAME=$(ls *.img | head -n 1)
     echo -e "Update using [ ${IMG_NAME} ] ] file. Please wait a moment ..."
-elif [ $( ls *.img.xz -l 2>/dev/null | grep "^-" | wc -l ) -ge 1 ]; then
-    xz_file=$( ls *.img.xz | head -n 1 )
+elif [ $(ls *.img.xz -l 2>/dev/null | grep "^-" | wc -l) -ge 1 ]; then
+    xz_file=$(ls *.img.xz | head -n 1)
     echo -e "Update using [ ${xz_file} ] file. Please wait a moment ..."
     xz -d ${xz_file} 2>/dev/null
-    IMG_NAME=$( ls *.img | head -n 1 )
-elif [ $( ls *.img.gz -l 2>/dev/null | grep "^-" | wc -l ) -ge 1 ]; then
-    gz_file=$( ls *.img.gz | head -n 1 )
+    IMG_NAME=$(ls *.img | head -n 1)
+elif [ $(ls *.img.gz -l 2>/dev/null | grep "^-" | wc -l) -ge 1 ]; then
+    gz_file=$(ls *.img.gz | head -n 1)
     echo -e "Update using [ ${gz_file} ] file. Please wait a moment ..."
     gzip -df ${gz_file} 2>/dev/null
-    IMG_NAME=$( ls *.img | head -n 1 )
-elif [ $( ls *.7z -l 2>/dev/null | grep "^-" | wc -l ) -ge 1 ]; then
-    gz_file=$( ls *.7z | head -n 1 )
+    IMG_NAME=$(ls *.img | head -n 1)
+elif [ $(ls *.7z -l 2>/dev/null | grep "^-" | wc -l) -ge 1 ]; then
+    gz_file=$(ls *.7z | head -n 1)
     echo -e "Update using [ ${gz_file} ] file. Please wait a moment ..."
     bsdtar -xmf ${gz_file} 2>/dev/null
     [ $? -eq 0 ] || 7z x ${gz_file} -aoa -y 2>/dev/null
-    IMG_NAME=$( ls *.img | head -n 1 )
-elif [ $( ls *.zip -l 2>/dev/null | grep "^-" | wc -l ) -ge 1 ]; then
-    zip_file=$( ls *.zip | head -n 1 )
+    IMG_NAME=$(ls *.img | head -n 1)
+elif [ $(ls *.zip -l 2>/dev/null | grep "^-" | wc -l) -ge 1 ]; then
+    zip_file=$(ls *.zip | head -n 1)
     echo -e "Update using [ ${zip_file} ] file. Please wait a moment ..."
     unzip -o ${zip_file} 2>/dev/null
-    IMG_NAME=$( ls *.img | head -n 1 )
+    IMG_NAME=$(ls *.img | head -n 1)
 else
     echo -e "Please upload or specify the update openwrt firmware file."
     echo -e "Upload method: system menu → Amlogic Service → Manually Upload Update"
@@ -93,16 +96,16 @@ fi
 sync
 
 # check file
-if  [ ! -f "${IMG_NAME}" ]; then
+if [ ! -f "${IMG_NAME}" ]; then
     echo "No update file found."
     exit 1
 else
     echo "Start update from [ ${IMG_NAME} ]"
 fi
 
-# find boot partition 
+# find boot partition
 BOOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/boot$/ {print $0}')
-if [ "${BOOT_PART_MSG}" == "" ];then
+if [ "${BOOT_PART_MSG}" == "" ]; then
     echo "The boot partition is not exists or not mounted, so it cannot be upgraded with this script!"
     exit 1
 fi
@@ -117,33 +120,38 @@ else
     read yn
 fi
 case $yn in
-     n*|N*) BR_FLAG=0;;
+n* | N*)
+    BR_FLAG=0
+    ;;
 esac
 
 BOOT_NAME=$(echo $BOOT_PART_MSG | awk '{print $1}')
 BOOT_PATH=$(echo $BOOT_PART_MSG | awk '{print $2}')
 BOOT_UUID=$(echo $BOOT_PART_MSG | awk '{print $4}')
 
-# find root partition 
+# find root partition
 ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | awk '$3~/^part$/ && $5 ~ /^\/$/ {print $0}')
 ROOT_NAME=$(echo $ROOT_PART_MSG | awk '{print $1}')
 ROOT_PATH=$(echo $ROOT_PART_MSG | awk '{print $2}')
 ROOT_UUID=$(echo $ROOT_PART_MSG | awk '{print $4}')
-case $ROOT_NAME in 
-    ${EMMC_NAME}${PARTITION_NAME}2) NEW_ROOT_NAME="${EMMC_NAME}${PARTITION_NAME}3"
-                    NEW_ROOT_LABEL="${LB_PRE}ROOTFS2"
-                    ;;
-    ${EMMC_NAME}${PARTITION_NAME}3) NEW_ROOT_NAME="${EMMC_NAME}${PARTITION_NAME}2"
-                    NEW_ROOT_LABEL="${LB_PRE}ROOTFS1"
-                    ;;
-    *) echo "The root partition location is invalid, so it cannot be upgraded with this script!"
-                    exit 1
-                    ;;
+case $ROOT_NAME in
+${EMMC_NAME}${PARTITION_NAME}2)
+    NEW_ROOT_NAME="${EMMC_NAME}${PARTITION_NAME}3"
+    NEW_ROOT_LABEL="${LB_PRE}ROOTFS2"
+    ;;
+${EMMC_NAME}${PARTITION_NAME}3)
+    NEW_ROOT_NAME="${EMMC_NAME}${PARTITION_NAME}2"
+    NEW_ROOT_LABEL="${LB_PRE}ROOTFS1"
+    ;;
+*)
+    echo "The root partition location is invalid, so it cannot be upgraded with this script!"
+    exit 1
+    ;;
 esac
 
 # find new root partition
 NEW_ROOT_PART_MSG=$(lsblk -l -o NAME,PATH,TYPE,UUID,MOUNTPOINT | grep "${NEW_ROOT_NAME}" | awk '$3 ~ /^part$/ && $5 !~ /^\/$/ && $5 !~ /^\/boot$/ {print $0}')
-if [ "${NEW_ROOT_PART_MSG}" == "" ];then
+if [ "${NEW_ROOT_PART_MSG}" == "" ]; then
     echo "The new root partition is not exists, so it cannot be upgraded with this script!"
     exit 1
 fi
@@ -154,9 +162,9 @@ NEW_ROOT_MP=$(echo $NEW_ROOT_PART_MSG | awk '{print $5}')
 
 # losetup
 losetup -f -P $IMG_NAME
-if [ $? -eq 0 ];then
+if [ $? -eq 0 ]; then
     LOOP_DEV=$(losetup | grep "$IMG_NAME" | awk '{print $1}')
-    if [ "$LOOP_DEV" == "" ];then
+    if [ "$LOOP_DEV" == "" ]; then
         echo "loop device not found!"
         exit 1
     fi
@@ -166,22 +174,22 @@ else
 fi
 WAIT=3
 echo -n "The loopdev is $LOOP_DEV, wait ${WAIT} seconds "
-while [ $WAIT -ge 1 ];do
+while [ $WAIT -ge 1 ]; do
     echo -n "."
     sleep 1
-    WAIT=$(( WAIT - 1 ))
+    WAIT=$((WAIT - 1))
 done
 echo
 
 # umount loop devices (openwrt will auto mount some partition)
 MOUNTED_DEVS=$(lsblk -l -o NAME,PATH,MOUNTPOINT | grep "$LOOP_DEV" | awk '$3 !~ /^$/ {print $2}')
-for dev in $MOUNTED_DEVS;do
-    while : ;do
+for dev in $MOUNTED_DEVS; do
+    while :; do
         echo -n "umount $dev ... "
         umount -f $dev
         sleep 1
         mnt=$(lsblk -l -o NAME,PATH,MOUNTPOINT | grep "$dev" | awk '$3 !~ /^$/ {print $2}')
-        if [ "$mnt" == "" ];then
+        if [ "$mnt" == "" ]; then
             echo "ok"
             break
         else
@@ -197,29 +205,29 @@ P2=${WORK_DIR}/root
 mkdir -p $P1 $P2
 echo -n "mount ${LOOP_DEV}p1 -> ${P1} ... "
 mount -t vfat -o ro ${LOOP_DEV}p1 ${P1}
-if [ $? -ne 0 ];then
+if [ $? -ne 0 ]; then
     echo "mount failed"
     losetup -D
     exit 1
-else 
+else
     echo "ok"
-fi	
+fi
 
 echo -n "mount ${LOOP_DEV}p2 -> ${P2} ... "
 mount -t btrfs -o ro,compress=zstd ${LOOP_DEV}p2 ${P2}
-if [ $? -ne 0 ];then
+if [ $? -ne 0 ]; then
     echo "mount failed"
     umount -f ${P1}
     losetup -D
     exit 1
 else
     echo "ok"
-fi	
+fi
 
 #format NEW_ROOT
 echo "umount ${NEW_ROOT_MP}"
 umount -f "${NEW_ROOT_MP}"
-if [ $? -ne 0 ];then
+if [ $? -ne 0 ]; then
     echo "umount failed, please reboot and try again!"
     umount -f ${P1}
     umount -f ${P2}
@@ -230,7 +238,7 @@ fi
 echo "format ${NEW_ROOT_PATH}"
 NEW_ROOT_UUID=$(uuidgen)
 mkfs.btrfs -f -U ${NEW_ROOT_UUID} -L ${NEW_ROOT_LABEL} ${NEW_ROOT_PATH}
-if [ $? -ne 0 ];then
+if [ $? -ne 0 ]; then
     echo "format ${NEW_ROOT_PATH} failed!"
     umount -f ${P1}
     umount -f ${P2}
@@ -240,7 +248,7 @@ fi
 
 echo "mount ${NEW_ROOT_PATH} to ${NEW_ROOT_MP}"
 mount -t btrfs -o compress=zstd ${NEW_ROOT_PATH} ${NEW_ROOT_MP}
-if [ $? -ne 0 ];then
+if [ $? -ne 0 ]; then
     echo "mount ${NEW_ROOT_PATH} to ${NEW_ROOT_MP} failed!"
     umount -f ${P1}
     umount -f ${P2}
@@ -252,13 +260,13 @@ fi
 cd ${NEW_ROOT_MP}
 echo "Start copy data from ${P2} to ${NEW_ROOT_MP} ..."
 ENTRYS=$(ls)
-for entry in $ENTRYS;do
-    if [ "$entry" == "lost+found" ];then
+for entry in $ENTRYS; do
+    if [ "$entry" == "lost+found" ]; then
         continue
     fi
     echo -n "remove old $entry ... "
     rm -rf $entry
-    if [ $? -eq 0 ];then
+    if [ $? -eq 0 ]; then
         echo "ok"
     else
         echo "failed"
@@ -278,7 +286,7 @@ echo
 
 COPY_SRC="root etc bin sbin lib opt usr www"
 echo "copy data ... "
-for src in $COPY_SRC;do
+for src in $COPY_SRC; do
     echo -n "copy $src ... "
     (cd ${P2} && tar cf - $src) | tar xf -
     sync
@@ -289,21 +297,21 @@ SHFS="/mnt/${EMMC_NAME}${PARTITION_NAME}4"
 echo "Modify config files ... "
 rm -f "./etc/rc.local.orig" "./etc/first_run.sh" "./etc/part_size"
 rm -f ./etc/bench.log
-if [ -x ./usr/sbin/balethirq.pl ];then
-    if grep "balethirq.pl" "./etc/rc.local";then
+if [ -x ./usr/sbin/balethirq.pl ]; then
+    if grep "balethirq.pl" "./etc/rc.local"; then
         echo "balance irq is enabled"
     else
         echo "enable balance irq"
         sed -e "/exit/i\/usr/sbin/balethirq.pl" -i ./etc/rc.local
     fi
 fi
-cat > ./etc/fstab <<EOF
+cat >./etc/fstab <<EOF
 UUID=${NEW_ROOT_UUID} / btrfs compress=zstd 0 1
 LABEL=${LB_PRE}BOOT /boot vfat defaults 0 2
 #tmpfs /tmp tmpfs defaults,nosuid 0 0
 EOF
 
-cat > ./etc/config/fstab <<EOF
+cat >./etc/config/fstab <<EOF
 config global
         option anon_swap '0'
         option anon_mount '1'
@@ -329,17 +337,17 @@ config mount
                 
 EOF
 (
-    cd etc/rc.d 
+    cd etc/rc.d
     rm -f S??shortcut-fe
-    if grep "sfe_flow '1'" ../config/turboacc >/dev/null;then
-        if find ../../lib/modules -name 'shortcut-fe-cm.ko';then
+    if grep "sfe_flow '1'" ../config/turboacc >/dev/null; then
+        if find ../../lib/modules -name 'shortcut-fe-cm.ko'; then
             ln -sf ../init.d/shortcut-fe S99shortcut-fe
         fi
     fi
 )
 
 # move /etc/config/balance_irq to /etc/balance_irq
-[ -f  "./etc/config/balance_irq" ] && mv ./etc/config/balance_irq  ./etc/
+[ -f "./etc/config/balance_irq" ] && mv ./etc/config/balance_irq ./etc/
 sync
 
 echo "create the first etc snapshot -> .snapshots/etc-000"
@@ -348,17 +356,17 @@ btrfs subvolume snapshot -r etc .snapshots/etc-000
 [ -d ${SHFS}/docker ] || mkdir -p ${SHFS}/docker
 rm -rf opt/docker && ln -sf ${SHFS}/docker/ opt/docker
 
-if [ -f /mnt/${NEW_ROOT_NAME}/etc/config/AdGuardHome ];then
+if [ -f /mnt/${NEW_ROOT_NAME}/etc/config/AdGuardHome ]; then
     [ -d ${SHFS}/AdGuardHome/data ] || mkdir -p ${SHFS}/AdGuardHome/data
-    if [ ! -L /usr/bin/AdGuardHome ];then
-        [ -d /usr/bin/AdGuardHome ] && \
-        cp -a /usr/bin/AdGuardHome/* ${SHFS}/AdGuardHome/
+    if [ ! -L /usr/bin/AdGuardHome ]; then
+        [ -d /usr/bin/AdGuardHome ] &&
+            cp -a /usr/bin/AdGuardHome/* ${SHFS}/AdGuardHome/
     fi
     ln -sf ${SHFS}/AdGuardHome /mnt/${NEW_ROOT_NAME}/usr/bin/AdGuardHome
 fi
 
 BOOTLOADER="./lib/u-boot/u-boot-sunxi-with-spl.bin"
-if [ -f ${BOOTLOADER} ];then
+if [ -f ${BOOTLOADER} ]; then
     echo "update u-boot ... "
     # erase from 8kb to 4mb
     dd if=/dev/zero of=/dev/${EMMC_NAME} bs=1024 seek=8 count=4088 conv=fsync
@@ -371,14 +379,14 @@ echo "copy done"
 echo
 
 BACKUP_LIST=$(${P2}/usr/sbin/openwrt-backup -p)
-if [ $BR_FLAG -eq 1 ];then
+if [ $BR_FLAG -eq 1 ]; then
     echo -n "Restore your old config files ... "
     (
         cd /
         eval tar czf ${NEW_ROOT_MP}/.reserved/openwrt_config.tar.gz "${BACKUP_LIST}" 2>/dev/null
     )
     tar xzf ${NEW_ROOT_MP}/.reserved/openwrt_config.tar.gz
-    [ -f ./etc/config/dockerman ] &&  sed -e "s/option wan_mode 'false'/option wan_mode 'true'/" -i ./etc/config/dockerman 2>/dev/null
+    [ -f ./etc/config/dockerman ] && sed -e "s/option wan_mode 'false'/option wan_mode 'true'/" -i ./etc/config/dockerman 2>/dev/null
     [ -f ./etc/config/dockerd ] && sed -e "s/option wan_mode '0'/option wan_mode '1'/" -i ./etc/config/dockerd 2>/dev/null
     [ -f ./etc/config/verysync ] && sed -e 's/config setting/config verysync/' -i ./etc/config/verysync
 
@@ -391,26 +399,26 @@ if [ $BR_FLAG -eq 1 ];then
 fi
 
 rm -f ./etc/bench.log
-cat >> ./etc/crontabs/root << EOF
+cat >>./etc/crontabs/root <<EOF
 17 3 * * * /etc/coremark.sh
 EOF
 
 sed -e 's/ttyAMA0/ttyS0/' -i ./etc/inittab
 sss=$(date +%s)
-ddd=$((sss/86400))
+ddd=$((sss / 86400))
 sed -e "s/:0:0:99999:7:::/:${ddd}:0:99999:7:::/" -i ./etc/shadow
 # 修复amule每次升级后重复添加条目的问题
 sed -e "/amule:x:/d" -i ./etc/shadow
 # 修复dropbear每次升级后重复添加sshd条目的问题
 sed -e "/sshd:x:/d" -i ./etc/shadow
-if [ `grep "sshd:x:22:22" ./etc/passwd | wc -l` -eq 0 ];then
-    echo "sshd:x:22:22:sshd:/var/run/sshd:/bin/false" >> ./etc/passwd
-    echo "sshd:x:22:sshd" >> ./etc/group
-    echo "sshd:x:${ddd}:0:99999:7:::" >> ./etc/shadow
+if [ $(grep "sshd:x:22:22" ./etc/passwd | wc -l) -eq 0 ]; then
+    echo "sshd:x:22:22:sshd:/var/run/sshd:/bin/false" >>./etc/passwd
+    echo "sshd:x:22:sshd" >>./etc/group
+    echo "sshd:x:${ddd}:0:99999:7:::" >>./etc/shadow
 fi
 
-if [ $BR_FLAG -eq 1 ];then
-    if [ -x ./bin/bash ] && [ -f ./etc/profile.d/30-sysinfo.sh ];then
+if [ $BR_FLAG -eq 1 ]; then
+    if [ -x ./bin/bash ] && [ -f ./etc/profile.d/30-sysinfo.sh ]; then
         sed -e 's/\/bin\/ash/\/bin\/bash/' -i ./etc/passwd
     fi
     sync
@@ -419,10 +427,10 @@ if [ $BR_FLAG -eq 1 ];then
 fi
 sed -e "s/option hw_flow '1'/option hw_flow '0'/" -i ./etc/config/turboacc
 (
-    cd etc/rc.d 
+    cd etc/rc.d
     rm -f S??shortcut-fe
-    if grep "sfe_flow '1'" ../config/turboacc >/dev/null;then
-        if find ../../lib/modules -name 'shortcut-fe-cm.ko';then
+    if grep "sfe_flow '1'" ../config/turboacc >/dev/null; then
+        if find ../../lib/modules -name 'shortcut-fe-cm.ko'; then
             ln -sf ../init.d/shortcut-fe S99shortcut-fe
         fi
     fi
@@ -432,7 +440,7 @@ eval tar czf .reserved/openwrt_config.tar.gz "${BACKUP_LIST}" 2>/dev/null
 
 rm -f ./etc/part_size ./etc/first_run.sh
 mv ./etc/rc.local ./etc/rc.local.orig
-cat > ./etc/rc.local <<EOF
+cat >./etc/rc.local <<EOF
 if [ ! -f /etc/rc.d/*dockerd ];then
     /etc/init.d/dockerd enable
     /etc/init.d/dockerd start
@@ -445,7 +453,7 @@ EOF
 chmod 755 ./etc/rc.local*
 
 # move /etc/config/balance_irq to /etc/balance_irq
-[ -f  "./etc/config/balance_irq" ] && mv ./etc/config/balance_irq  ./etc/
+[ -f "./etc/config/balance_irq" ] && mv ./etc/config/balance_irq ./etc/
 
 echo "create the second etc snapshot -> .snapshots/etc-001"
 btrfs subvolume snapshot -r etc .snapshots/etc-001
@@ -456,20 +464,20 @@ btrfs subvolume snapshot -r etc .snapshots/etc-001
 #chattr +ia ./etc/config/fstab
 
 cd ${WORK_DIR}
- 
+
 echo "Start copy data from ${P1} to /boot ..."
 cd /boot
 echo -n "remove old boot files ..."
 rm -rf *
 echo "done"
-echo -n "copy new boot files ... " 
-(cd ${P1} && tar cf - . ) | tar xf -
+echo -n "copy new boot files ... "
+(cd ${P1} && tar cf - .) | tar xf -
 sync
 echo "done"
 echo
 
 echo -n "Update boot args ... "
-cat > uEnv.txt <<EOF
+cat >uEnv.txt <<EOF
 LINUX=/zImage
 INITRD=/uInitrd
 
@@ -494,4 +502,3 @@ echo "Successfully updated, automatic restarting..."
 sleep 3
 reboot
 exit 0
-
